oc-server-attributes:
  groups:
    -
      name: global
      comment: 全局通用配置
      attributes:
        -
          name: global_enable_public_ip_mgmt
          value: false
          content: "启用公网ip管理，此配置将作用于:zabbix,jumpserver,keybox"
        -
          name: ssh_port
          value: 22
          content: "ssh端口"
        -
          name: platform
          value: Linux
          content: "平台类型"
    -
      name: ansible
      comment: Ansible属性配置项
      attributes:
        -
          name: ansible_subgroup
          value: 0
          content: "分组模式, 0按默认算法分组"
    -
      name: zabbix
      comment: Zabbix属性配置项
      attributes:
        -
          name: zabbix_bidirectional_sync
          value: false
          content: "双向同步(会清理多余的模版)"
        -
          name: zabbix_host_macros
          value: ''
          content: 'JSONArray格式:[{"macro": "{$USER_ID}","value": "1"} ]'
        -
          name: zabbix_templates
          value: ''
          content: '模版名称（多个用,分割）'
        -
          name: zabbix_sysdisk_volume_name
          value: ''
          content: '系统盘卷标'
        -
          name: zabbix_datadisk_volume_name
          value: ''
          content: '数据盘卷标'
        -
          name: zabbix_proxy
          value: ''
          content: '代理名称'